#!/usr/bin/env python3
# :mode=python:
#
# PP_to_pico
# 
# Quick-push just the updated files to the Pico

import os
from pathlib import Path
import subprocess
import sys
import time

DBG = False
PRT = True
V = False
VV = False
# global so that perr() can access
STOP_ON_ERROR = True

HELP_INFO="""
PP_to_pico  <options>  DEST-DEVICE  ...page-dirs...
Options:
  --help            Show this help.  [-h]
  --quiet           Quiet mode  [-q]
  --verbose         Verbose mode [-v]
  --veryverbose     Very verbose  [-V, -vv, --vv]
  --stop-on-error   Stop if any error  [--stop, -X]
  --force-update    Force copying all files to the device; ignores marker files.  [-F, --force]
  --dryrun          Dry run: do not copy to device.  [-Y, -N]
  --force-marker-file-update  Perform an update ('touch') the marker files, even if dryrun.  [-U]
  --debug           Debug  [-Z, -z]
  --debug_itself    Debug the options processing.  [--z, --Z, --zoption, --zoptions]

DEST-DEVICE is  
  /dev/ttyACM0 or a0
  /dev/ttyACM1 or a1
  /dev/ttyACM2 or a2
  /dev/ttyACM3 or a3
NOTE that you must define PREM_DEVICE so that the PP_to_pico alias can work.
You can use the USE_A0,... aliases to do this.

The page-dirs are 'pages', etc.
Specify ALL for all directories - which is the default if none are specified.
"""

MARKER_FILENAME_TEMPLATE = "__PPUSH_MARKER__{mpremote_device}"

DEVICE_TO_IDENTIFIER = {
    "a0":               "a0",
    "A0":               "a0",
    "/dev/ttyACM0":     "a0",
    "/dev/ttyacm0":     "a0",

    "a1":               "a1",
    "A1":               "a1",
    "/dev/ttyACM1":     "a1",
    "/dev/ttyacm1":     "a1",

    "a2":               "a2",
    "A2":               "a2",
    "/dev/ttyACM2":     "a2",
    "/dev/ttyacm2":     "a2",

    "a3":               "a3",
    "A3":               "a3",
    "/dev/ttyACM3":     "a3",
    "/dev/ttyacm3":     "a3",
    }

# aka pages folders
ALL_DIRS=[
     "pages",
     "pages_big_files",
    ]
# map local-pages-dir to remote dir
REMOTE_DIRS = {
    "pages":            "pages",
    "pages_big_files":  "pages",
    }


class ToPico:
    def __init__(self):
        #@@@@@@@@@@@@@@@@@@ RENAME
        self.page_dir_names = []
        # Force copying to the device regards of timestamps on the files
        self._force_update = False
        # Dry run - do not copy to device
        self._dryrun = False
        # Perform a 'touch' update on marker files. Normally disabled for
        # dryrun, but can be forced using an option.
        self._do_marker_file_touch = True

    def do_options(self, opts):
        global DBG, V, VV, STOP_ON_ERROR, PRT
        #print(f"@22 opts={opts}")
        if opts.debug: DBG = True
        if opts.verbose: V = True
        if opts.veryverbose: VV = True; V = True
        if opts.quiet: PRT = False
        
        if opts.dryrun: 
            self._dryrun = True
            # Do not update the marker file timestamp - unless FORCED
            self._do_marker_file_touch = False
            if opts.force_marker_file_update: self._do_marker_file_touch = True

        if opts.stop_on_error: STOP_ON_ERROR = True
        if opts.force_update: self._force_update = True
        # 'a0', 'a1',...
        self._device_identifier = None
        # __QPUSH_MARKER__a0, etc.
        self._marker_filename = None


        if len(opts.other_items) <= 0:
            print(f"do_options@58 YOU MUST INCLUDE A DESTINATION DEVICE!")
            print(f"               Try --help")
            raise RuntimeError(f"do_options@58 YOU MUST INCLUDE A DESTINATION DEVICE on the command line!")

        # First non-option item must be a destination device 
        dev_stg = opts.other_items[0]
        requested_dirs = opts.other_items[1:]

        if V: print(f"PP@125  Device '{dev_stg}'   Directories-requested: '{requested_dirs}' ")

        dev_id = DEVICE_TO_IDENTIFIER.get(dev_stg)
        if not dev_id:
            raise RuntimeError(f"PP@129 Unknown mpremote device: '{dev_stg}'")
        self._device_identifier = dev_id

        if len(requested_dirs) == 0: requested_dirs = ["ALL"]
        if "ALL" in requested_dirs:
            if len(requested_dirs) != 1:
                perr(f"PP@135 The 'ALL' pseudo-directory-name must be specified by itself; no other dirs allowed.")
                sys.exit(1)
            d_names = set(ALL_DIRS)
        else:
            d_names = set(requested_dirs)
        # Verify the directory names are known to us
        for d_n in d_names:
            if d_n not in ALL_DIRS:
                perr(f"PP@143 Unrecognized package name '{d_n}'")
                sys.exit(1)
        # Create a list of requested dirs, in order per ALL_DIRS
        self.page_dir_names = []
        for d_name in ALL_DIRS:
            if d_name in d_names:
                self.page_dir_names.append(d_name)
        if V: print(f"PP@150 Dirs to be copied: {self.page_dir_names}")


    def run(self):
        if DBG or V:
            print(f"PP@155{DBG=}  {V=}  veryV={VV} PRT={PRT} stop_on_error={STOP_ON_ERROR}  ")
        if self._dryrun: print("PP@156  ----------- DRY RUN  -------------------------")

        for page_dir_name in self.page_dir_names:
            self.do_page_directory(page_dir_name)


    def do_page_directory(self, page_dir_name):
        if V: print(f"\n+++ Pages Directory: {page_dir_name}  -------")

        local_dir_path = Path("./"+page_dir_name)
        if not local_dir_path.is_dir():
            perr(f"No such local_dir_path page dir: {local_dir_path}  {page_dir_name=}")
            return

        self._marker_filename = MARKER_FILENAME_TEMPLATE.format(mpremote_device=self._device_identifier)
        if V: print(f"Marker filename='{self._marker_filename}'")

        # Get the marker file
        marker_fpath = local_dir_path / self._marker_filename
        if V: print(f"PP@187  {marker_fpath=}")

        if marker_fpath.is_dir():
            perr(f"PP@190 The marker is a DIRECTORY; expected a FILE!  '{marker_fpath}'")
        if not marker_fpath.exists():
            if PRT: print(f"PP@192  -- Marker file {marker_fpath} does not exist.  Creating it now...")
            self._create_marker_file(marker_fpath)
        else:
            if V: print(f"PP@195 -- Marker file {marker_fpath} exists. ")
        marker_ts = self._get_file_timestamp(marker_fpath)
        if V: print(f"PP@197 marker TIMESTAMP {marker_ts} ")
        if self._force_update:
            marker_ts = 0
            if V: print(f"PP@200 marker FORCE UPDATE: zero the marker TIMESTAMP {marker_ts} ")

        filenames = self._get_files_in_dir(local_dir_path)
        if V: print(f"PP@203 FILENAMES {filenames} " )

        files_and_ts = list()
        for fname in filenames:
            ts = self._get_file_timestamp(local_dir_path / fname)
            files_and_ts.append ( (fname, ts) )
        if V: 
            print(f"PP@210 files_and_ts: ")
            for fname, ts in files_and_ts:
                diff = ts - marker_ts
                print(f"  {fname:>25s} {ts:10.1f} {diff:10.1f}")

        chosen_fnames = list()
        for fname, ts in files_and_ts:
            if VV: print(f"PP@217 {fname=}  {ts=}")
            if ts >= marker_ts:
                chosen_fnames.append(fname)
            else:
                if VV: print(f"PP@221  OLD, not chosen:   {fname} ts={ts}   marker={marker_ts} ")
        if V: print(f"PP@222 Files to be copied: {chosen_fnames}")

        remote_dir_path_stg = REMOTE_DIRS.get(str(local_dir_path))

        self._copy_to_pico(local_dir_path, remote_dir_path_stg, chosen_fnames)

        num_copied = len(chosen_fnames)
        if num_copied > 1:
            if PRT: print(f"PP@228 Copied {num_copied} files from {page_dir_name} to the PICO.")
        elif num_copied == 1:
            if PRT: print(f"PP@230 Copied 1 file to the PICO  {page_dir_name}")
        else:
            if PRT: print(f"PP@232  NO FILES copied to the PICO  {page_dir_name}")

        # Update the marker's timestamp(s)
        if not self._do_marker_file_touch: 
            print(f"PP@236: _do_marker_file_touch: FALSE!  Marker file '{marker_fpath}' TIMESTAMP has *NOT* been updated!")
        else:
            self._set_file_timestamps_to_now(marker_fpath)
            if V:
                ts = self._get_file_timestamp(marker_fpath)
                print(f"PP@241  Marker file '{marker_fpath}' TIMESTAMP updated to {ts:.1f}")


    def _copy_to_pico(self, local_dir_path, remote_dir_path_stg, chosen_fnames):

        if V: print(f"PP@252  str(local_dir_path)='{str(local_dir_path)}'  remote_dir_path_stg='{remote_dir_path_stg}' ")
        cmd_and_args = (
                "mpremote", "fs", "mkdir", 
                f":/{remote_dir_path_stg}")
        self._run_a_command(cmd_and_args, ignore_failure=True)

        for fname in chosen_fnames:
            cmd_and_args = (
                "mpremote", "fs", "cp", 
                str(local_dir_path/fname), f":/{remote_dir_path_stg}/")
            self._run_a_command(cmd_and_args)


    def _run_a_command(self, cmd_and_args, ignore_failure=False):
        # cmd_and_args is a list: ['cmd', 'arg', ...]
        # Run the command and capturing its output
        if V: print(f"PP@260  RUN CMD: {cmd_and_args} ")
        if self._dryrun:
            print(f"PP@262  DRY RUN: not performed:  {' '.join(cmd_and_args)}")
            return

        result = subprocess.run(cmd_and_args, capture_output=True, text=True)

        if VV: print("PP@267  Return code:", result.returncode)
        if VV: print("PP@268 STDOUT:", result.stdout)
        if VV: print("PP@269 STDERR:", result.stderr)

        # Check if the command was successful (return code 0)
        if result.returncode != 0:
            if ignore_failure:
                if V: print(f"PP@274     IGNORED FAILED command {cmd_and_args} failed!   RESULT-CODE={result.returncode} ")
            else:
                perr(f"PP@276 Command {cmd_and_args} failed!   RESULT-CODE={result.returncode} ")


    def _get_files_in_dir(self, local_dir_path):
        files = list()
        for fname in os.listdir(local_dir_path):
            # skip dirs, etc
            if not os.path.isfile(os.path.join(local_dir_path, fname)):
                continue
            if fname == self._marker_filename:
                continue
            files.append(fname)
        return files


    def _create_marker_file(self, marker_fpath):
        if VV: print(f"PP@292 Create marker file: '{marker_fpath}' ")
        with open(marker_fpath, "w") as f:
            pass
        access_time = 100000
        modification_time = 100001
        os.utime(marker_fpath, (access_time, modification_time))

    def _get_file_timestamp(self, fpath):
        s = os.stat(fpath)
        if VV: print(f"PP@301  fpath={fpath}  status={s} ")
        return s.st_mtime

    def _set_file_timestamps_to_now(self, fpath):
        secs = time.time()
        access_time = secs
        modification_time = secs
        os.utime(fpath, (access_time, modification_time) )



def perr(err):
    print(f"**ERROR**  {err}")
    if STOP_ON_ERROR:
        raise RuntimeError(f"STOPPING DUE TO ERROR: {err}")



####################################################################

class SimpleOptionsParser(object):
    """ Simplified options parser """

    class _Options(object):
        """ """
        def __init__(self):
            """ """

        @property
        def optionNames(self):
            """ Returns a collection of str: the property names
            of the option values.
            """
            names = []
            for n in self.__dict__.keys():
                if n.startswith("_"): continue
                names.append(n)
            return names

        def __str__(self):
            """ """
            s = []
            for name in self.optionNames:
                val = getattr(self, name)
                s.append(f"{name}={val}")
            return f"{self.__class__.__name__}[{','.join(s)}]"
        __repr__ = __str__


    ################################################################

    def parseOptions(self, args):
        """ """

        opts = SimpleOptionsParser._Options()

        # Items that are not options (do not start with '-' or '--')
        opts.other_items = []

        opts.verbose = False
        opts.veryverbose = False
        opts.debug = False
        opts.force_update = False
        opts.dryrun = False
        opts.force_marker_file_update = False
        opts.quiet = False
        opts.stop_on_error = False

        argidx = 0
        debug_itself = False
        while argidx < len(args):

            arg = args[argidx]; argidx += 1

            if debug_itself: print(f"PP@375 arg is '{arg}'")

            if arg.startswith("--"):
                opt_stg = arg[2:]
            elif arg.startswith("-"):
                opt_stg = arg[1:]
            else:
                if debug_itself: print(f"PP@382 NOT AN OPT {arg}")
                opts.other_items.append(arg)
                continue

            ####optLc = opt.lower()
            ###if debug_itself: print(f"PP@387  OPT is {opt}    {optLc=} ")
            if debug_itself: print(f"PP@388  OPT is {opt}  ")

            if opt_stg in ("help","h"):
                print(HELP_INFO)
                sys.exit(1)

            elif opt_stg in ("q", "quiet"):
                opts.quiet = True

            elif opt_stg in ("v", "verbose"):
                opts.verbose = True

            elif opt_stg in ("V", "vv", "veryverbose"):
                opts.verbose = True
                opts.veryverbose = True
                print("VERY VERBOSE MODE")

            elif opt_stg in ("X", "stop", "stop-on-error"):
                opts.debug = True

            elif opt_stg in ("F", "force", "force-update",):
                opts.force_update = True

            elif opt_stg in ("N", "Y","y", "dry", "dryrun",):
                opts.dryrun = True

            elif opt_stg in ("U", "force-marker-file-update",):
                opts.force_marker_file_update = True

            elif opt_stg in ("Z", "z", "debug"):
                opts.stop_on_error = True

            elif opt_stg in ("zz", "ZZ", "zoption", "zoptions", "debug_itself"):
                debug_itself = True

            # elif self._isInt(opt):
                # ival = int(opt)
                # opts.dataSets.append(ival)
    
            else:
                s = f"*ERROR* Unknown option '{arg}'"
                if not opt_stg:
                    s = "*ERROR Stand-alone option marker disallowed:  '-' or '--' by itself."
                raise RuntimeError(s)

        if debug_itself:
            print(f"PP@434 $$$ SimpleOptionsParser Args: {args}")
            print(f"PP@435 parsed options: {opts}")

        return opts


    ################################################################

    def _isInt(self, stg):
        try:
            _ = int(stg)
            return True
        except (ValueError, TypeError):
            pass
        return False

    ################################################################

    def runTests(self):
        """ Run some simple tests """

        if 1:
            opts = self.parseOptions(["-zoptions", "-v"])
            print(f"PP@457  +++ opts={opts}")
            assert opts.verbose is True
            assert opts.veryverbose is False
            assert req_items == []
        if 1:
            opts = self.parseOptions(["-zoptions", "a", "b"])
            print(f"PP@463  +++ opts={opts}")
            assert req_items == ["a", "b"]


def main(args):
    opts = SimpleOptionsParser().parseOptions(args)
    to_pico = ToPico()
    to_pico.do_options(opts)
    print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ DRYRUN IS FORECED at line 465@@@@@@@@@@@@@@@@@@@@@@@@@@")
    to_pico._dryrun = True # @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    to_pico.run()

if __name__ == "__main__":
    main(sys.argv[1:])

# :mode=python:

###
